'use client';

import { motion, AnimatePresence } from 'framer-motion';
import GlassCard from './GlassCard';
import { X, Download, ShieldCheck } from 'lucide-react';

interface ReportModalProps {
    isOpen: boolean;
    onClose: () => void;
    type: 'wealth' | 'academic';
    data: any; // In real app, define specific types
}

export default function ReportModal({ isOpen, onClose, type, data }: ReportModalProps) {
    const isWealth = type === 'wealth';
    const title = isWealth ? 'Investment Intelligence Report' : 'Academic Pathway Report';
    const colorClass = isWealth ? 'text-accent-blue' : 'text-accent-orange';
    const borderClass = isWealth ? 'border-accent-blue/20' : 'border-accent-orange/20';

    return (
        <AnimatePresence>
            {isOpen && (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-navy-900/80 backdrop-blur-sm"
                    onClick={onClose}
                >
                    <motion.div
                        initial={{ scale: 0.9, y: 20 }}
                        animate={{ scale: 1, y: 0 }}
                        exit={{ scale: 0.9, y: 20 }}
                        className="w-full max-w-2xl"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <GlassCard variant="dark" className="relative p-0 overflow-hidden border-white/10 shadow-2xl">
                            {/* Header */}
                            <div className="flex items-center justify-between p-6 border-b border-white/5 bg-white/5">
                                <div className="flex items-center gap-3">
                                    <div className={`p-2 rounded-lg bg-white/5 border ${borderClass}`}>
                                        <ShieldCheck className={`w-5 h-5 ${colorClass}`} />
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-white">{title}</h3>
                                        <p className="text-xs text-white/40 flex items-center gap-2">
                                            <span>Generated by Eduk8u AI</span>
                                            <span className="w-1 h-1 bg-white/20 rounded-full" />
                                            <span className="flex items-center gap-1 text-emerald-400"><ShieldCheck className="w-3 h-3" /> Time-Locked: {new Date().toLocaleDateString()}</span>
                                        </p>
                                    </div>
                                </div>
                                <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-full transition-colors text-white/60">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>

                            {/* Content */}
                            <div className="p-8 space-y-6 max-h-[60vh] overflow-y-auto">
                                {/* Summary Section */}
                                <div className="space-y-2">
                                    <h4 className="text-sm font-semibold text-white/60 uppercase tracking-widest">Executive Summary</h4>
                                    <p className="text-white/90 leading-relaxed font-light">
                                        Based on the inputs provided for {isWealth ? 'a capital allocation' : 'an academic trajectory'} of <span className="font-mono font-bold text-white">{isWealth ? `$${data.amount}` : data.goal}</span>,
                                        our algorithmic models project a {isWealth ? 'high-confidence growth corridor' : 'strong alignment with global market demand'}.
                                        The primary indicators suggest {isWealth ? 'optimal risk-adjusted returns' : 'positive ROI within 24 months'}.
                                    </p>
                                </div>

                                {/* Key Metrics Grid */}
                                <div className="grid grid-cols-2 gap-4">
                                    {isWealth ? (
                                        <>
                                            <MetricBox label="Projected Value (10yr)" value={data.bestCase} color="text-emerald-400" />
                                            <MetricBox label="Risk Adjusted Return" value={data.expectedReturn} color="text-accent-blue" />
                                            <MetricBox label="Max Drawdown Risk" value="-8.4%" color="text-rose-400" />
                                            <MetricBox label="Liquidity Score" value="High (A+)" color="text-white" />
                                        </>
                                    ) : (
                                        <>
                                            <MetricBox label="Est. Starting Salary" value={data.projectedIncome} color="text-emerald-400" />
                                            <MetricBox label="Employability Score" value={data.probability} color="text-accent-orange" />
                                            <MetricBox label="Total Education Cost" value={data.cost} color="text-white" />
                                            <MetricBox label="Global Mobility" value="Visa Ready" color="text-accent-blue" />
                                        </>
                                    )}
                                </div>

                                {/* Disclaimer */}
                                <div className="p-4 rounded-lg bg-white/5 border border-white/5 text-[10px] text-white/30 leading-relaxed">
                                    <p>DISCLAIMER: This report is generated by an AI model for simulation purposes only. It does not constitute financial advice or an offer to sell securities. Past performance is not indicative of future results. Educational outcomes vary based on individual performance and economic conditions.</p>
                                </div>
                            </div>

                            {/* Footer Actions */}
                            <div className="p-6 border-t border-white/5 bg-white/5 flex gap-4">
                                <button className="flex-1 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-medium transition-colors border border-white/10 text-sm flex items-center justify-center gap-2">
                                    <Download className="w-4 h-4" /> Download PDF
                                </button>
                                <button className={`flex-1 py-3 text-navy-900 font-bold rounded-xl transition-colors text-sm ${isWealth ? 'bg-accent-blue hover:bg-accent-blue/90' : 'bg-accent-orange hover:bg-accent-orange/90'}`}>
                                    Book Advisory Call
                                </button>
                            </div>

                        </GlassCard>
                    </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    );
}

function MetricBox({ label, value, color }: { label: string, value: string, color: string }) {
    return (
        <div className="p-4 rounded-xl bg-white/5 border border-white/5">
            <p className="text-xs text-white/40 mb-1">{label}</p>
            <p className={`text-lg font-bold font-mono ${color}`}>{value}</p>
        </div>
    )
}
